### ISSUE TITLE
Sync item already processed. Ignored

### ISSUE THREAD

**Issue by reflash** [kory-smith/todoist-api-ts#17]
Hi!

I was trying to use todoist api to create multiple tasks, but for some reason I can't create more then 1 with the same client
I get the following error message - Request failed with status code 400 - Sync item already processed. Ignored

The tasks have different content, so I'm wondering what is stopping me from creating a bunch of them at the same time

**Comment by kory-smith** [comment]
Hey. I'm looking into this. Can you confirm that you're using the most recent version (1.1.3 as of my writing this)? I've been doing a bunch of updates recently.

Interestingly, I'm also unable to make multiple new tasks, but I'm just getting a 500.

**Comment by reflash** [comment]
> Hey. I'm looking into this. Can you confirm that you're using the most recent version (1.1.3 as of my writing this)? I've been doing a bunch of updates recently.
> 
> Interestingly, I'm also unable to make multiple new tasks, but I'm just getting a 500.

Thanks!
I've been using 1.2.0, isn't it the latest one?

**Comment by kory-smith** [comment]
Yes, 1.2.0. The versions bumps are automated and I hadn't pulled 🤦🏻.

I tried switching the HTTP client from Axios to Got (which I'm more fond of anyway) and I was able to make two tasks in a row with no issues. I'll probably make a PR to migrate and link this issue. Thanks for being patient.

**Comment by kory-smith** [comment]
Hey @reflash, would you do me the favor of confirming you're still experiencing the same issue? I was able to duplicate your issue in the past, but now I'm successfully able to create as many tasks with the main instance as I'd like.

With any luck, this was an issue on Todoist's end and we're clear.

**Comment by reflash** [comment]
> Hey @reflash, would you do me the favor of confirming you're still experiencing the same issue? I was able to duplicate your issue in the past, but now I'm successfully able to create as many tasks with the main instance as I'd like.
> 
> With any luck, this was an issue on Todoist's end and we're clear.

I can't really confirm that, no longer using Todoist :/ I this issue could be closed safely though

**Comment by kory-smith** [comment]
All good! Shortly after I took over this repo, I found that Todoist has an official TS API, so this repo is obsolete anyway.
