### ISSUE TITLE
Base URL has changed

### ISSUE THREAD

**Issue by garyking** [kory-smith/todoist-api-ts#3]
https://github.com/ManuKle/todoist-api-ts/blob/f4b61e3cff677e7496b10298032124e110664653/src/TodoistApiREST.ts#L25

Here are the new docs: https://developer.todoist.com/rest/v1/

Otherwise, the endpoints haven't changed.

Old: `https://beta.todoist.com/API/v8/`
New: `https://api.todoist.com/rest/v1/`

**Comment by kory-smith** [comment]
Updated in c1f1bee
